name: PlatformIO CI

on: [push]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            .pio/build/pico/firmware.elf
            .pio/build/pico/firmware.bin
            .pio/build/pico/firmware.bin.signed
            .pio/build/pico/firmware.uf2

